### ISSUE TITLE
Request/Contribution: Expanding Parsing - Typing Command Messages: Missing Command, Unsupported Command, Supported Command

### ISSUE THREAD

**Issue by GalGreenfield** [campbellbrendene/discord-command-parser#18]
Hello,

Right now I'm using the parser and it works great.

I think adding types to command type functionality would be great:

 - Expanding `discord.js`'sMessageTypes to include a `COMMAND` type
 - Adding `CommandMessageType` to messages  where `message.type == COMMAND`
    - `missing` - missing command: when `message.content == prefix`)
    - `unsupported` - unsupported command: when `message.command` is not supported by the bot)
    - `supported` - supported command: when `message.command` is supported by the bot)

This will enable easy classification, handling and maybe more, of command messages.

Right now the parser behaves in that I don't like for the case of a missing `missing` commands: technically if `message.content == prefix`, the message's content is not a command - however, I think it'd be better to assume that it's an attempt for a command where the author just forgot to add a command - why else would someone would send a message that is just the prefix of the bot (and know it to begin with, if they don't have permission to use the bot)?

I'm actually working on this (and handling these different types of commands) right now, and I've love to contribute the code for that if you're interested (written in pure JS).

**Comment by campbellbrendene** [comment]
Hi GalGreenfield,

Thank you for this suggestion. An extension of the discord.js `MessageType` structure seems like it would be quite useful.

However, I believe it is out-of-scope for this project, as it maintains support for both [eris](https://github.com/abalabahaha/eris) as well as discord.js. Therefore, there cannot be any library-specific code or structures such as this.

I have been considering creating a more in-depth, library-independent command library using this project as a dependency. Perhaps something like what you're suggesting will make sense to include there. I'll reference this issue if/when that comes up.

Thank you for the suggestion, nonetheless. For now, I would suggest creating this utility specific to your bot, perhaps as a `discord-extensions.js` file or similar.

**Comment by GalGreenfield** [comment]
Right, I forgot that this library is also intended for eris.

I'm building it pretty general-purpose for handling commands and messages - after I finish it I'll publish it. 
Would you like me to link you to it after I publish it?

Also, what's exactly a `discord-extension.js` file? I couldn't find much information about that.

**Comment by campbellbrendene** [comment]
> I'm building it pretty general-purpose for handling commands and messages - after I finish it I'll publish it.
Would you like me to link you to it after I publish it?

I currently have plans to create a library similar to this concept, as a complementary library to this one. However, I'm sure your implementation will be interesting to see!

> Also, what's exactly a `discord-extension.js` file? I couldn't find much information about that.

This is just an example filename. I merely was suggesting that you have *some* file dedicated to contain your custom extensions to discord.js.

**Comment by GalGreenfield** [comment]
What kind of extensions were you talking about? I just found out about discord.js-plugins - is that what you were referring to?
