### ISSUE TITLE
 Responding to a mention instead of a prefix

### ISSUE THREAD

**Issue by MrZillaGold** [campbellbrendene/discord-command-parser#7]
Add the ability to use the mention of the bot instead of the prefix, it will be useful if the user forgot the bot prefix

Example:
!hello args
@mrzillagold hello args

**Comment by campbellbrendene** [comment]
Thank you for the suggestion!

I believe this could already be done with:
```ts
const parsed = parser.parse(message, [
  "!",
  `<@${client.user.id}>`,
  `<@!${client.user.id}>`,
], {
  allowSpaceBeforeCommand: true,
});
